### ISSUE TITLE
PHP Fatal error with IntlCalendar

### ISSUE THREAD

**Issue by sitex** [CakeDC/Intl#2]
```PHP Fatal error:  Cannot use IntlCalendar as IntlCalendar because the name is already in use in /vendor/cakedc/intl/src/IntlGregorianCalendar.php on line 14```

**Comment by OneHatRepo** [comment]
Fix as follows:

/vendor/cakedc/intl/src/IntGregorianCalendar.php

Change line 14 to be:
`use CakeDC\Intl\IntlCalendar;`

**Comment by steinkel** [comment]
fix applied to master
